name: zbenv
channels:
  - conda-forge
  - defaults
dependencies:
  - abseil-cpp=20211102.0
  - appdirs=1.4.4
  - arrow-cpp=14.0.2
  - aws-c-auth=0.6.19
  - aws-c-cal=0.5.20
  - aws-c-common=0.8.5
  - aws-c-compression=0.2.16
  - aws-c-event-stream=0.2.15
  - aws-c-http=0.6.25
  - aws-c-io=0.13.10
  - aws-c-mqtt=0.7.13
  - aws-c-s3=0.1.51
  - aws-c-sdkutils=0.1.6
  - aws-checksums=0.1.13
  - aws-crt-cpp=0.18.16
  - aws-sdk-cpp=1.10.55
  - blas=2.121
  - blas-devel=3.9.0
  - boost-cpp=1.84.0
  - bottleneck=1.3.8
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.28.1
  - ca-certificates=2024.2.2
  - certifi=2024.2.2
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - cryptography=42.0.5
  - et_xmlfile=1.1.0
  - gflags=2.2.2
  - glog=0.5.0
  - grpc-cpp=1.48.2
  - icu=73.2
  - idna=3.6
  - jinja2=3.1.3
  - joblib=1.3.2
  - krb5=1.21.2
  - libabseil=20211102.0
  - libblas=3.9.0
  - libboost=1.84.0
  - libboost-devel=1.84.0
  - libboost-headers=1.84.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=8.7.1
  - libcxx=16.0.6
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libiconv=1.17
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libnghttp2=1.58.0
  - libopenblas=0.3.26
  - libprotobuf=3.20.3
  - libsqlite=3.45.2
  - libssh2=1.11.0
  - libthrift=0.15.0
  - libzlib=1.2.13
  - llvm-openmp=18.1.2
  - lz4-c=1.9.4
  - markupsafe=2.1.5
  - ncurses=6.4.20240210
  - numexpr=2.9.0
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openblas=0.3.26
  - openpyxl=3.1.2
  - openssl=3.2.1
  - orc=1.7.4
  - packaging=24.0
  - pandas=2.2.1
  - patsy=0.5.6
  - pip=24.0
  - platformdirs=4.2.0
  - pooch=1.8.1
  - pyarrow=14.0.2
  - pycparser=2.22
  - pyopenssl=24.0.0
  - pysocks=1.7.1
  - python=3.9.19
  - python-dateutil=2.9.0
  - python-tzdata=2024.1
  - python_abi=3.9
  - pytz=2024.1
  - re2=2022.04.01
  - readline=8.2
  - requests=2.31.0
  - scipy=1.13.0
  - setuptools=69.2.0
  - six=1.16.0
  - snappy=1.1.10
  - sqlite=3.45.2
  - statsmodels=0.14.1
  - tk=8.6.13
  - tqdm=4.66.2
  - tzdata=2024a
  - urllib3=2.2.1
  - utf8proc=2.6.1
  - wheel=0.43.0
  - xlrd=2.0.1
  - xz=5.2.6
  - zlib=1.2.13
  - zstd=1.5.5

